In [3]:
import pandas as pd
import numpy as np
import glob
import os
import datetime

In [37]:
files_path = "Data/CollegeScorecard_Raw_Data"
read_files = glob.glob(os.path.join(files_path,"*.csv"))

college_data = []
for file in read_files:
#     print(file)
    year = file[-14:-7]
    year_data = pd.DataFrame(pd.read_csv(file))
    year_data['YEAR'] = year
    
    year_data = year_data[['UNITID','INSTNM','CITY', 'ZIP','INSTURL','ADM_RATE','ADM_RATE_ALL', 'TUITIONFEE_IN','YEAR']]
    
    college_data.append(year_data)

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1,1408,1431,1432,1433,1489,1537,1538,1539,1540,1542,1606,1610,1611,1614,1615,1616,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (6,1169,1170,1171,1172,1173,1174,1175,1177,1178,1179,1180,1183,1184,1185,1186,1187,1188,1196,1199,1200,1209,1212,1213,1222,1223,1224,1225,1226,1227,1235,1236,1237,1238,1239,1240,1248,1251,1252,1253,1255,1257,1261,1264,1265,1266,1268,1270,1274,1275,1276,1277,1278,1279,1281,1287,1288,1289,1290,1291,1292,1294,1303,1304,1316,1317,1326,1327,1328,1329,1330,1331,1335,1339,1340,1341,1342,1343,1344,1348,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1411,1426,1427,1475,1476,1479,1480,1483,1484,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1517,1529,1530,1532,1537,1540,1541,1542,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1606,1609,1610,1613,1614,1615,1708,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1537,1540,1542,1575,1606,1614,1615,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (6,9,31,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (6,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1431,1432,1503,1504,1517,1518,1519,1529,1530,1531,1532,1534,1535,1537,1538,1539,1540,1542,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1606,1610,1611,1614,1615,1616,1708,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1,6,442,451,598,607,611,620,624,633,789,802,806,815,971,984,997,1153,1166,1407,1408,1411,1424,1425,1426,1431,1432,1433,1437,1438,1439,1440,1445,1446,1447,1451,1452,1453,1454,1459,1460,1461,1465,1466,1467,1468,1473,1474,1475,1479,1480,1481,1482,1487,1488,1489,1501,1502,1537,1538,1539,1540,1541,1542,1606,1609,1610,1611,1613,1614,1615,1616,1688,1689,1690,1691,1692,1908,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (6,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1537,1540,1542,1547,1548,1549,1561,1575,1606,1614,1615,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1,1447,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (1,6,1461,1561,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [38]:
sample = college_data[0]
sample

,UNITID,INSTNM,CITY,ZIP,INSTURL,ADM_RATE,ADM_RATE_ALL,TUITIONFEE_IN,YEAR
0,100654,Alabama A & M University,Normal,35762,NaN,0.5010,0.5010,6828.0,2011_12
1,100663,University of Alabama at Birmingham,Birmingham,35294-0110,NaN,0.7223,0.7223,6264.0,2011_12
2,100690,Amridge University,Montgomery,36117-3553,NaN,NaN,NaN,8720.0,2011_12
3,100706,University of Alabama in Huntsville,Huntsville,35899,NaN,0.6368,0.6368,8094.0,2011_12
4,100724,Alabama State University,Montgomery,36104-0271,NaN,0.5080,0.5080,8082.0,2011_12
5,100751,The University of Alabama,Tuscaloosa,35487-0166,NaN,0.4353,0.4353,8600.0,2011_12
6,100760,Central Alabama Community College,Alexander City,35010,NaN,NaN,NaN,2700.0,2011_12
7,100812,Athens State University,Athens,35611,NaN,NaN,NaN,NaN,2011_12
8,100830,Auburn University at Montgomery,Montgomery,36117-3596,NaN,0.7894,0.7894,7580.0,2011_12
9,100858,Auburn University,Auburn,36849,NaN,0.7000,0.7000,8698.0,2011_12
10,100937,Birmingham Southern College,Birmingham,35254,NaN,0.6418,0.6418,29290.0,2011_12
11,101028,Chattahoochee Valley Community College,Phenix City,36869,NaN,NaN,NaN,4140.0,2011_12
12,101073,Concordia College Alabama,Selma,36701,NaN,NaN,NaN,8090.0,2011_12
13,101116,South University-Montgomery,Montgomery,36116,NaN,0.5533,0.6630,15910.0,2011_12
14,101143,Enterprise State Community College,Enterprise,36330-1300,NaN,NaN,NaN,3668.0,2011_12
15,101161,Coastal Alabama Community College,Bay Minette,36507-2698,NaN,NaN,NaN,4080.0,2011_12
16,101189,Faulkner University,Montgomery,36109-3390,NaN,0.5802,0.5802,15880.0,2011_12
17,101240,Gadsden State Community College,Gadsden,35903,NaN,NaN,NaN,3780.0,2011_12
18,101277,New Beginning College of Cosmetology,Albertville,35951,NaN,NaN,NaN,NaN,2011_12
19,101286,George C Wallace Community College-Dothan,Dothan,36303-9234,NaN,NaN,NaN,3330.0,2011_12
20,101295,George C Wallace State Community College-Hance...,Hanceville,35077-2000,NaN,NaN,NaN,4080.0,2011_12
21,101301,George C Wallace State Community College-Selma,Selma,36703-2808,NaN,NaN,NaN,3780.0,2011_12
22,101365,Herzing University-Birmingham,Birmingham,35209,NaN,0.9790,0.9933,11040.0,2011_12
23,101435,Huntingdon College,Montgomery,36106-2148,NaN,0.6199,0.6199,21990.0,2011_12
24,101453,Heritage Christian University,Florence,35630-9977,NaN,NaN,NaN,12030.0,2011_12
25,101462,J. F. Drake State Community and Technical College,Huntsville,35811,NaN,NaN,NaN,3144.0,2011_12
26,101480,Jacksonville State University,Jacksonville,36265,NaN,0.8365,0.8365,6120.0,2011_12
27,101499,Jefferson Davis Community College,Brewton,36426,NaN,NaN,NaN,3788.0,2011_12
28,101505,Jefferson State Community College,Birmingham,35215-3098,NaN,NaN,NaN,4140.0,2011_12
29,101514,John C Calhoun State Community College,Tanner,35671,NaN,NaN,NaN,3480.0,2011_12
...,...,...,...,...,...,...,...,...,...
7645,45316306,Strayer University-South Raleigh Campus,Raleigh,27603,NaN,NaN,NaN,14805.0,2011_12
7646,45321501,Strayer University-Willingboro Campus,Willingboro,08046,NaN,NaN,NaN,14805.0,2011_12
7647,45321502,Strayer University-Lawrenceville,Lawrenceville,08648,NaN,NaN,NaN,14805.0,2011_12
7648,45321503,Strayer University-Piscataway,Piscataway,08854,NaN,NaN,NaN,14805.0,2011_12
7649,45484701,National Beauty College,Denver,802231991,NaN,NaN,NaN,NaN,2011_12
7650,45486501,Cambridge College of Healthcare & Technology,Atlanta,303421731,NaN,NaN,NaN,NaN,2011_12
7651,45538101,Utah County Campus,Orem,840580000,NaN,NaN,NaN,NaN,2011_12
7652,45666701,Strayer University-Columbus Campus,Columbus,43240,NaN,NaN,NaN,14805.0,2011_12
7653,45666702,Strayer University-Fairview Park Campus,Fairview Park,44126,NaN,NaN,NaN,14805.0,2011_12
7654,45666703,Strayer University-Akron Campus,Akron,44320,NaN,NaN,NaN,14805.0,2011_12
7655,45712901,Chamberlain College of Nursing-Miramar Campus,Miramar,33027,NaN,NaN,0.8121,NaN,2011_12
7656,45891901,Strayer University-Cobb Campus,Atlanta,30339,NaN,NaN,NaN,14805.0,2011_12
7657,45891902,Strayer University-Morrow Campus,Morrow,30260,NaN,NaN,NaN,14805.0,2011_12
7658,45891903,Strayer University-Roswell Campus,Roswell,30076,NaN,NaN,NaN,14805.0,2011_12
7659,45891904,Strayer University-Douglasville Campus,Douglasville,30135,NaN,NaN,NaN,14805.0,2011_12
7660,45891905,Strayer University-Lithonia Campus,Lithonia,30038,NaN,NaN,NaN,14805.0,2011_12
7661,45891906,Strayer University-Savannah Campus,Savannah,31419,NaN,NaN,NaN,14805.0,2011_12
7662,45891907,Strayer University-Augusta Campus,Augusta,30909,NaN,NaN,NaN,14805.0,2011_12
7663,45891908,Strayer University-Columbus,Columbus,31909,NaN,NaN,NaN,14805.0,2011_12
7664,45896401,Strayer University-Columbia Campus,Columbia,29210,NaN,NaN,NaN,14805.0,2011_12
7665,45896402,Strayer University-Charleston Campus,North Charleston,29418,NaN,NaN,NaN,14805.0,2011_12
7666,45897301,Strayer University-Irving,Irving,75063,NaN,NaN,NaN,14805.0,2011_12
7667,45897302,Strayer University-Katy,Houston,77079,NaN,NaN,NaN,14805.0,2011_12
7668,45897303,Strayer University-Northwest Houston,Houston,77064,NaN,NaN,NaN,14805.0,2011_12
7669,45897304,Strayer University-Plano,Plano,75093,NaN,NaN,NaN,14805.0,2011_12
7670,45920401,Unitek College,Fremont,945383185,NaN,NaN,NaN,17192.0,2011_12
7671,46163401,Twin Rivers Adult School - Grand Avenue Center,Sacramento,95838-3654,NaN,NaN,NaN,NaN,2011_12
7672,46163402,Twin Rivers Adult School - Arnold Avenue Center,McClellan,956521025,NaN,NaN,NaN,NaN,2011_12
7673,46163403,Greater Sacramento Urban League,Sacramento,958383738,NaN,NaN,NaN,NaN,2011_12
7674,46163404,I-TAP,Sacramento,95841-2989,NaN,NaN,NaN,NaN,2011_12

In [19]:
college_data[0].columns

Index(['UNITID', 'OPEID', 'OPEID6', 'INSTNM', 'CITY', 'STABBR', 'ZIP',
       'ACCREDAGENCY', 'INSTURL', 'NPCURL',
       ...
       'OMAWDP8_NOTFIRSTTIME_POOLED_SUPP', 'OMENRUP_NOTFIRSTTIME_POOLED_SUPP',
       'OMENRYP_FULLTIME_POOLED_SUPP', 'OMENRAP_FULLTIME_POOLED_SUPP',
       'OMAWDP8_FULLTIME_POOLED_SUPP', 'OMENRUP_FULLTIME_POOLED_SUPP',
       'OMENRYP_PARTTIME_POOLED_SUPP', 'OMENRAP_PARTTIME_POOLED_SUPP',
       'OMAWDP8_PARTTIME_POOLED_SUPP', 'OMENRUP_PARTTIME_POOLED_SUPP'],
      dtype='object', length=1977)

In [24]:
sample_col = sample[['UNITID','INSTNM','CITY', 'ZIP','INSTURL','NPCURL','ADM_RATE','ADM_RATE_ALL', 'TUITIONFEE_IN']]

In [39]:
data = np.vstack(college_data)
data = pd.DataFrame(data)
data.columns = ['UNITID','INSTNM','CITY', 'ZIP','INSTURL','NPCURL','ADM_RATE','ADM_RATE_ALL', 'TUITIONFEE_IN']

In [40]:
data

,UNITID,INSTNM,CITY,ZIP,INSTURL,NPCURL,ADM_RATE,ADM_RATE_ALL,TUITIONFEE_IN
0,100654,Alabama A & M University,Normal,35762,NaN,0.501,0.501,6828,2011_12
1,100663,University of Alabama at Birmingham,Birmingham,35294-0110,NaN,0.7223,0.7223,6264,2011_12
2,100690,Amridge University,Montgomery,36117-3553,NaN,NaN,NaN,8720,2011_12
3,100706,University of Alabama in Huntsville,Huntsville,35899,NaN,0.6368,0.6368,8094,2011_12
4,100724,Alabama State University,Montgomery,36104-0271,NaN,0.508,0.508,8082,2011_12
5,100751,The University of Alabama,Tuscaloosa,35487-0166,NaN,0.4353,0.4353,8600,2011_12
6,100760,Central Alabama Community College,Alexander City,35010,NaN,NaN,NaN,2700,2011_12
7,100812,Athens State University,Athens,35611,NaN,NaN,NaN,NaN,2011_12
8,100830,Auburn University at Montgomery,Montgomery,36117-3596,NaN,0.7894,0.7894,7580,2011_12
9,100858,Auburn University,Auburn,36849,NaN,0.7,0.7,8698,2011_12
10,100937,Birmingham Southern College,Birmingham,35254,NaN,0.6418,0.6418,29290,2011_12
11,101028,Chattahoochee Valley Community College,Phenix City,36869,NaN,NaN,NaN,4140,2011_12
12,101073,Concordia College Alabama,Selma,36701,NaN,NaN,NaN,8090,2011_12
13,101116,South University-Montgomery,Montgomery,36116,NaN,0.5533,0.663,15910,2011_12
14,101143,Enterprise State Community College,Enterprise,36330-1300,NaN,NaN,NaN,3668,2011_12
15,101161,Coastal Alabama Community College,Bay Minette,36507-2698,NaN,NaN,NaN,4080,2011_12
16,101189,Faulkner University,Montgomery,36109-3390,NaN,0.5802,0.5802,15880,2011_12
17,101240,Gadsden State Community College,Gadsden,35903,NaN,NaN,NaN,3780,2011_12
18,101277,New Beginning College of Cosmetology,Albertville,35951,NaN,NaN,NaN,NaN,2011_12
19,101286,George C Wallace Community College-Dothan,Dothan,36303-9234,NaN,NaN,NaN,3330,2011_12
20,101295,George C Wallace State Community College-Hance...,Hanceville,35077-2000,NaN,NaN,NaN,4080,2011_12
21,101301,George C Wallace State Community College-Selma,Selma,36703-2808,NaN,NaN,NaN,3780,2011_12
22,101365,Herzing University-Birmingham,Birmingham,35209,NaN,0.979,0.9933,11040,2011_12
23,101435,Huntingdon College,Montgomery,36106-2148,NaN,0.6199,0.6199,21990,2011_12
24,101453,Heritage Christian University,Florence,35630-9977,NaN,NaN,NaN,12030,2011_12
25,101462,J. F. Drake State Community and Technical College,Huntsville,35811,NaN,NaN,NaN,3144,2011_12
26,101480,Jacksonville State University,Jacksonville,36265,NaN,0.8365,0.8365,6120,2011_12
27,101499,Jefferson Davis Community College,Brewton,36426,NaN,NaN,NaN,3788,2011_12
28,101505,Jefferson State Community College,Birmingham,35215-3098,NaN,NaN,NaN,4140,2011_12
29,101514,John C Calhoun State Community College,Tanner,35671,NaN,NaN,NaN,3480,2011_12
...,...,...,...,...,...,...,...,...,...
154198,45057102,Rasmussen College-Wausau,Wausau,544017804,NaN,NaN,0.8379,13560,2010_11
154199,45312701,Strayer University-Louisville Campus,Louisville,40223,NaN,NaN,NaN,14085,2010_11
154200,45312702,Strayer University-Florence Campus,Florence,41042,NaN,NaN,NaN,14085,2010_11
154201,45316301,Strayer University-North Charlotte,Charlotte,28027,NaN,NaN,NaN,14085,2010_11
154202,45316302,Strayer University-South Charlotte,Charlotte,28273,NaN,NaN,NaN,14085,2010_11
154203,45316303,Strayer University-North Raleigh Campus,Raleigh,27616,NaN,NaN,NaN,14085,2010_11
154204,45316304,Strayer University-Greensboro Campus,Greensboro,27407,NaN,NaN,NaN,14085,2010_11
154205,45316305,Strayer University-Huntersville Campus,Raleigh,28078,NaN,NaN,NaN,14085,2010_11
154206,45316306,Strayer University-South Raleigh Campus,Raleigh,27603,NaN,NaN,NaN,14085,2010_11
154207,45321501,Strayer University-Willingboro Campus,Willingboro,8046,NaN,NaN,NaN,14085,2010_11
154208,45321502,Strayer University-Lawrenceville,Lawrenceville,8648,NaN,NaN,NaN,14085,2010_11
154209,45321503,Strayer University-Piscataway,Piscataway,8854,NaN,NaN,NaN,14085,2010_11
154210,45666701,Strayer University-Columbus Campus,Columbus,43240,NaN,NaN,NaN,14085,2010_11
154211,45666702,Strayer University-Fairview Park Campus,Fairview Park,44126,NaN,NaN,NaN,14085,2010_11
154212,45666703,Strayer University-Akron Campus,Akron,44320,NaN,NaN,NaN,14085,2010_11
154213,45786401,Finger Lakes School of Massage,Mt. Kisco,10549,NaN,NaN,0.7232,NaN,2010_11
154214,45891901,Strayer University-Cobb Campus,Atlanta,30339,NaN,NaN,NaN,14085,2010_11
154215,45891902,Strayer University-Morrow Campus,Morrow,30260,NaN,NaN,NaN,14085,2010_11
154216,45891903,Strayer University-Roswell Campus,Roswell,30076,NaN,NaN,NaN,14085,2010_11
154217,45891904,Strayer University-Douglasville Campus,Douglasville,30135,NaN,NaN,NaN,14085,2010_11
154218,45891905,Strayer University-Lithonia Campus,Lithonia,30038,NaN,NaN,NaN,14085,2010_11
154219,45891906,Strayer University-Savannah Campus,Savannah,31419,NaN,NaN,NaN,14085,2010_11
154220,45891907,Strayer University-Augusta Campus,Augusta,30909,NaN,NaN,NaN,14085,2010_11
154221,45891908,Strayer University-Columbus,Columbus,31909,NaN,NaN,NaN,14085,2010_11
154222,45896401,Strayer University-Columbia Campus,Columbia,29210,NaN,NaN,NaN,14085,2010_11
154223,45896402,Strayer University-Charleston Campus,North Charleston,29418,NaN,NaN,NaN,14085,2010_11
154224,45897301,Strayer University-Irving,Irving,75063,NaN,NaN,NaN,14085,2010_11
154225,45897302,Strayer University-Katy,Houston,77079,NaN,NaN,NaN,14085,2010_11
154226,45897303,Strayer University-Northwest Houston,Houston,77064,NaN,NaN,NaN,14085,2010_11
154227,45897304,Strayer University-Plano,Plano,75093,NaN,NaN,NaN,14085,2010_11

In [30]:
print(file)

Data/CollegeScorecard_Raw_Data/MERGED2010_11_PP.csv

In [34]:
file[-14:-7]

'2010_11'